FROM tomcat:8
 
RUN locale-gen zh_CN.UTF-8 && \
    dpkg-reconfigure --frontend noninteractive locales && \
    apt-get update -qqy && \
    apt-get -qqy --no-install-recommends install ttf-wqy-zenhei && \
    rm -rf /var/lib/apt/lists/*
 
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN:zh
ENV LC_ALL zh_CN.UTF-8