apiVersion: v1
kind: ConfigMap
metadata:
  name: "nginx-proxy-master-config"
  namespace: ops-system
data:
  nginx.conf: |
    worker_processes  auto;

    error_log  /dev/stderr warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  65535;
    }


    http {
        default_type  application/octet-stream;

        log_format  main  '\$remote_addr - \$remote_user [\$time_local] "\$request" '
                          '\$status \$body_bytes_sent "\$http_referer" '
                          '"\$http_user_agent" "\$http_x_forwarded_for"';

        access_log  /dev/stdout  main;

        sendfile        on;
        #tcp_nopush     on;


        keepalive_timeout  65;

    }
    stream {
        log_format proxy '$remote_addr [$time_local] '
                     '$protocol $status $bytes_sent $bytes_received '
                     '$session_time "$upstream_addr" '
                     '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time"';

        upstream stream_proxy {
            server xxx;
        }
        server {
            listen 44379;
            proxy_pass stream_proxy;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tcp-proxy
  namespace: ops-system
  labels:
    app: nginx-tcp-proxy
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tcp-proxy
  template:
    metadata:
      labels:
        app: nginx-tcp-proxy
        version: v1
    spec:
      hostNetwork: true
      tolerations:
        - effect: NoExecute
          key: special
          operator: Equal
          value: ops
      containers:
      - name: nginx
        image: slzcc/nginx:tcp-proxy
        env:
        - name: TZ
          value: "Asia/Shanghai"
        volumeMounts:
        - mountPath: "/etc/nginx/root"
          name: master
        - mountPath: /usr/share/zoneinfo
          name: usr-local-timezone
          readOnly: true
      securityContext:
        fsGroup: 0
        runAsUser: 0
      volumes:
      - name: usr-local-timezone
        hostPath:
          path: /usr/share/zoneinfo
          type: DirectoryOrCreate
      - name: master
        configMap:
          name: nginx-proxy-master-config