apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-lifecycles-nginx-sleep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox-lifecycles-nginx-sleep
  template:
    metadata:
      labels:
        app: busybox-lifecycles-nginx-sleep
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - image: slzcc/terminal-ctl:ubuntu-20.04
        imagePullPolicy: Always
        command:
          - nginx
          - -g
          - daemon off;
        name: busybox
        lifecycle:
          preStop:
           exec:
             command:
             - /bin/sh -c sleep 120
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: busybox-lifecycles-nginx-sleep
  labels:
    app: busybox-lifecycles-nginx-sleep
spec:
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP
  selector:
    app: busybox-lifecycles-nginx-sleep
