apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-nginx
  template:
    metadata:
      labels:
        app: busybox-nginx
    spec:
      terminationGracePeriodSeconds: 70
      containers:
      - image: slzcc/terminal-ctl:ubuntu-20.04
        args:
          - nginx
          - -g
          - daemon off;
        name: busybox
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: busybox-nginx
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: busybox-nginx